# Generated by Django 3.1 on 2020-08-07 03:24

from django.db import migrations, models
import django.db.models.deletion
import place.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('category', models.CharField(choices=[('rule', '相關規範'), ('admin', '所有權/管理單位'), ('sponsor', '認養單位')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='RelatedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=place.models.get_image_path)),
                ('url', models.URLField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=500)),
                ('name_code', models.CharField(max_length=500)),
                ('vernacular_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('place_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='用地類型')),
                ('action_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='推動形式')),
                ('link', models.URLField(blank=True, null=True, verbose_name='相簿與討論區')),
                ('cover_url', models.URLField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lon', models.TextField(blank=True, null=True)),
                ('tree_info', models.TextField(blank=True, null=True)),
                ('check_info', models.TextField(blank=True, null=True)),
                ('administrator', models.ForeignKey(blank=True, limit_choices_to={'category': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_places', to='place.link')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'category': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_places', to='place.link')),
                ('species_list', models.ManyToManyField(related_name='places', to='place.Species')),
                ('sponsor', models.ForeignKey(blank=True, limit_choices_to={'category': 'sponsor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_places', to='place.link')),
            ],
        ),
        migrations.CreateModel(
            name='UnlimitedCitiesImage',
            fields=[
                ('relatedimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.relatedimage')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlimited_cities_images', to='place.place')),
            ],
            bases=('place.relatedimage',),
        ),
        migrations.CreateModel(
            name='LandScriptImage',
            fields=[
                ('relatedimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='place.relatedimage')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='land_script_images', to='place.place')),
            ],
            bases=('place.relatedimage',),
        ),
    ]
