# Generated by Django 3.0.8 on 2020-07-26 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('place_type', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('cover', models.TextField(blank=True, null=True)),
                ('lat', models.TextField(blank=True, null=True)),
                ('lon', models.TextField(blank=True, null=True)),
                ('x97', models.TextField(blank=True, null=True)),
                ('y97', models.TextField(blank=True, null=True)),
                ('organization', models.TextField(blank=True, null=True)),
                ('action', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('filter', models.TextField(blank=True, null=True)),
                ('desc_long', models.TextField(blank=True, null=True)),
                ('desc_detailed', models.TextField(blank=True, null=True)),
                ('button_label', models.TextField(blank=True, null=True)),
                ('is_multi', models.TextField(blank=True, null=True)),
                ('shape_area', models.TextField(blank=True, null=True)),
                ('size_available', models.TextField(blank=True, null=True)),
                ('replant_size', models.TextField(blank=True, null=True)),
                ('revised_replant_size', models.TextField(blank=True, null=True)),
                ('unit', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
