# Generated by Django 3.1 on 2020-08-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='contact',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'contact'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_places', to='place.link'),
        ),
        migrations.AddField(
            model_name='place',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(choices=[('rule', '相關規範'), ('admin', '所有權/管理單位'), ('sponsor', '認養單位'), ('contact', '諮詢對象-民間/公部門'), ('nursery', '苗圃'), ('garden', '植物園與環教場所'), ('case', '參考綠化案例')], max_length=32),
        ),
    ]
