# Generated by Django 3.1 on 2020-08-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20200807_0441'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='place',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='place',
            name='check_info',
        ),
        migrations.RemoveField(
            model_name='place',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='place',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='place',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='place',
            name='tree_info',
        ),
        migrations.AddField(
            model_name='place',
            name='administrator_text',
            field=models.TextField(blank=True, verbose_name='管理單位'),
        ),
        migrations.AddField(
            model_name='place',
            name='case_text',
            field=models.TextField(blank=True, verbose_name='參考綠化案例'),
        ),
        migrations.AddField(
            model_name='place',
            name='contact_text',
            field=models.TextField(blank=True, verbose_name='諮詢對象-民間/公部門'),
        ),
        migrations.AddField(
            model_name='place',
            name='garden_text',
            field=models.TextField(blank=True, verbose_name='植物園與環教場所'),
        ),
        migrations.AddField(
            model_name='place',
            name='nursery_text',
            field=models.TextField(blank=True, verbose_name='苗圃'),
        ),
        migrations.AddField(
            model_name='place',
            name='owner_text',
            field=models.TextField(blank=True, verbose_name='所有權單位'),
        ),
        migrations.AddField(
            model_name='place',
            name='rule_text',
            field=models.TextField(blank=True, verbose_name='相關規範'),
        ),
        migrations.AddField(
            model_name='place',
            name='sponsor_text',
            field=models.TextField(blank=True, verbose_name='認養單位'),
        ),
    ]
