# Generated by Django 3.1 on 2020-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20200807_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='action_type',
            field=models.CharField(blank=True, choices=[('vision', '【願景蒐集型】'), ('adopt', '【代管認養型】我要認養'), ('donate-gov', '【捐款型】支認公部門綠化業務'), ('donate-ngo', '【捐款型】支持民間認養單位'), ('environ', '【環境復育型】')], max_length=500, null=True, verbose_name='推動形式'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cover_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
