# Generated by Django 3.1 on 2020-08-09 18:17

from django.db import migrations, models
import place.models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20200809_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='species',
            name='locality',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='place',
            name='lat',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='lon',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='species_list',
            field=models.ManyToManyField(blank=True, related_name='places', to='place.Species'),
        ),
        migrations.AlterField(
            model_name='relatedimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=place.models.get_image_path),
        ),
    ]
