# Generated by Django 3.1 on 2020-08-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20200809_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='species',
            name='locality',
            field=models.TextField(blank=True, default=''),
        ),
    ]
