# Generated by Django 4.0.5 on 2022-06-08 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_species_image_list'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'ordering': ['-image_list']},
        ),
    ]
